
package models.disease;

import models.Lifeform;

import org.junit.Test;

public class DiseaseTest {

    @Test
    public void nextDay_A$() throws Exception {

        // TODO auto-generated by JUnit Helper.
        final Lifeform carrier = null;
        final Disease target = new Disease(carrier);
        target.nextDay();
    }

}
