
package models;

import java.util.ArrayList;
import java.util.List;

import models.disease.Disease;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.Test;

public class LifeformTest {

    @Test
    public void isImmune_A$Disease() throws Exception {

        // TODO auto-generated by JUnit Helper.
        final int column = 0;
        final int line = 0;
        final Lifeform target = new Lifeform(column, line);
        final Disease disease = null;
        final boolean actual = target.isImmune(disease);
        final boolean expected = false;
        Assert.assertThat(actual,
                CoreMatchers.is(CoreMatchers.equalTo(expected)));
    }

    @Test
    public void nextDay_A$List$List() throws Exception {

        // TODO auto-generated by JUnit Helper.
        final int column = 0;
        final int line = 0;
        final Lifeform target = new Lifeform(column, line);
        final List<Lifeform> neighbors = new ArrayList<Lifeform>();
        final List<Cardinal> freeSpace = new ArrayList<Cardinal>();
        target.nextDay(neighbors, freeSpace);
    }

    @Test
    public void willChangeGridState_A$() throws Exception {

        // TODO auto-generated by JUnit Helper.
        final int column = 0;
        final int line = 0;
        final Lifeform target = new Lifeform(column, line);
        final boolean actual = target.willChangeGridState();
        final boolean expected = false;
        Assert.assertThat(actual,
                CoreMatchers.is(CoreMatchers.equalTo(expected)));
    }

}
